POST http://localhost:3001/api/v1/extract
Content-Type: application/json

{
  "userId": "garimpei_user_01",
  "url": "https://amzn.to/4cRA99K"
  //"url": "https://www.amazon.com.br/Proteínas-Chocolate-Banana-Brasil-Unidades/dp/B07XGM1BM7/ref=pd_bxgy_thbs_d_sccl_1/144-1848423-5967805?pd_rd_w=Jgz1v&content-id=amzn1.sym.ea5263f5-901f-4a74-9b73-3fc0e530788d&pf_rd_p=ea5263f5-901f-4a74-9b73-3fc0e530788d&pf_rd_r=Y24WAYAF5FHTDT9NDSGJ&pd_rd_wg=uxCTV&pd_rd_r=cb692e48-1dc2-4479-bff9-e16014fb4881&pd_rd_i=B07XGM1BM7&psc=1"
}

###

POST http://localhost:3001/api/v1/extract
Content-Type: application/json

{
  "userId": "garimpei_user_01",
  "url": "https://meli.la/1yjEbf9"
  //"url": "https://produto.mercadolivre.com.br/MLB-4210056475-relogio-masculino-de-pulso-social-classico-casual-original-_JM#reco_item_pos=1&reco_backend=item_decorator&reco_backend_type=function&reco_client=home_items-decorator-legacy&reco_id=bf280dd9-cb57-4ca2-8d6e-bb015c459e77&reco_model=&c_id=/home/navigation-trends-recommendations/element&c_uid=8ce38009-add0-4581-9385-9d9b8c74ccae&da_id=navigation_trend&da_position=1&id_origin=/home/dynamic_access&da_sort_algorithm=ranker"
}

###