POST http://localhost:3001/api/v1/extract
Content-Type: application/json

{
  "userId": "garimpei_user_03",
  "url": "https://www.amazon.com.br/YoPRO-Bebida-Láctea-Chocolate-proteínas/dp/B0CXF9FZ94/?_encoding=UTF8&pd_rd_w=G2uSN&content-id=amzn1.sym.0a72930b-1a9e-43b6-9305-46cb6f69d2a2&pf_rd_p=0a72930b-1a9e-43b6-9305-46cb6f69d2a2&pf_rd_r=BBBFECT3D8KPYR1XFQ8A&pd_rd_wg=6DJZB&pd_rd_r=d423069e-eef1-4619-8c84-79a2398a1e28&ref_=pd_hp_d_atf_br-star-asins-wd"
}

###