POST http://localhost:3001/api/v1/extract
Content-Type: application/json

{
  "userId": "garimpei_user_01",
  "url": "https://amzn.to/4cRA99K"
  //"url": "https://www.amazon.com.br/Proteínas-Chocolate-Banana-Brasil-Unidades/dp/B07XGM1BM7/ref=pd_bxgy_thbs_d_sccl_1/144-1848423-5967805?pd_rd_w=Jgz1v&content-id=amzn1.sym.ea5263f5-901f-4a74-9b73-3fc0e530788d&pf_rd_p=ea5263f5-901f-4a74-9b73-3fc0e530788d&pf_rd_r=Y24WAYAF5FHTDT9NDSGJ&pd_rd_wg=uxCTV&pd_rd_r=cb692e48-1dc2-4479-bff9-e16014fb4881&pd_rd_i=B07XGM1BM7&psc=1"
}

###

POST http://localhost:3001/api/v1/extract
Content-Type: application/json

{
  "userId": "garimpei_user_01",
  "url": "https://meli.la/1yjEbf9"
  //"url": "https://produto.mercadolivre.com.br/MLB-4210056475-relogio-masculino-de-pulso-social-classico-casual-original-_JM#reco_item_pos=1&reco_backend=item_decorator&reco_backend_type=function&reco_client=home_items-decorator-legacy&reco_id=bf280dd9-cb57-4ca2-8d6e-bb015c459e77&reco_model=&c_id=/home/navigation-trends-recommendations/element&c_uid=8ce38009-add0-4581-9385-9d9b8c74ccae&da_id=navigation_trend&da_position=1&id_origin=/home/dynamic_access&da_sort_algorithm=ranker"
}

###

POST http://localhost:3001/api/v1/config/cookies
Content-Type: application/json

{
  "userId": "garimpei_user_01",
  "cookies": "ssid=ghy-031018-y2KA6dKdeVjPvre8ltP6haVZREA1Vx-__-757601996-__-1867876738920--RRR_0-RRR_0; _d2id=8b86aec1-0669-4da3-923c-69b7f72d75f9; _csrf=eGDBgAzFovLMuunanq_ZnAuv; x-meli-session-id=armor.426b8af2d20f89c8bcb0aadee63843da4170d4b8735f434a6ec6f74af8be42a4c52ead02057547a7218b231829efdd6350136dd4878923cf0095711e627b17259339aa28bcb0a71cef6a6eca9c75f45475fb4b6281c2d803194beceb03a596ee.8b940b62a6a06b29d70a0a930bbb4c9d; ftid=lvs7e88uapMTqPdUIbn6ZGtxIRAc0Vwn-1769963432595",
  "tag": "garimpei"
}

###

POST http://localhost:3001/api/v1/config/api
Content-Type: application/json

{
  "userId": "garimpei_user_01",
  "tag": "ogarimpei-20"
}

###